[package]
name = "hive"
version = "0.1.0"
authors = ["Will"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
"criterion" = "*"

[[bench]]
name = "sgf_benchmark"
harness = false
